application: namespace
destinationNamespace: argo
createNamespace: false
sources:
  - repoURL: https://github.com/pelindung-bumi/galaksi
    targetRevision: HEAD
    path: overlays/pelindung-bumi/prod/namespace
