apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pelindung-bumi-prod
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Pelindung Bumi Production Project
  
  sourceRepos:
    - '*'
    
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
      
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
