cluster:
  name: pelindung-bumi

routingMode: native
ipv4NativeRoutingCIDR: 10.42.0.0/16

k8sServiceHost: 10.200.0.177
k8sServicePort: 6443

enableIPv4Masquerade: true
egressMasqueradeInterfaces: ens3

bpf:
  masquerade: true

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi

operator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

hubble:
  enabled: true
  relay:
    enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
  ui:
    enabled: true
    backend:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
    frontend:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
