apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: pelindung-bumi-prod
  sources:
    - repoURL: https://charts.external-secrets.io
      targetRevision: 0.14.0
      path: external-secrets
      helm:
        releaseName: external-secrets
        valueFiles:
          - $values/base/external-secrets/values/values-common.yaml
          - $values/overlays/pelindung-bumi/prod/external-secrets/values/values.yaml
    - repoURL: https://github.com/pelindung-bumi/galaksi
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/pelindung-bumi/galaksi
      targetRevision: HEAD
      path: base/external-secrets/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
