apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: pelindung-bumi-prod
  sources:
    - repoURL: https://github.com/pelindung-bumi/samudera
      targetRevision: rook-1.19.2
      path: charts/rook-ceph
      helm:
        releaseName: rook-ceph
        valueFiles:
          - $values/base/rook/operator/values/values-common.yaml
          - $values/overlays/pelindung-bumi/prod/rook/operator/values/values.yaml
    - repoURL: https://github.com/pelindung-bumi/galaksi
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
