toolbox:
  enabled: true

clusterName: rook-ceph

cephImage:
  repository: quay.io/ceph/ceph
  tag: v19.2.3

monitoring:
  enabled: false

pspEnable: false

cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.3
    imagePullPolicy: IfNotPresent
  dashboard:
    enabled: true
    ssl: false
  storage:
    useAllNodes: true
    useAllDevices: false

cephFileSystems: []
cephObjectStores: []
