application: envoy-gateway
destinationNamespace: envoy-gateway-system
createNamespace: false
syncOptions:
  - ServerSideApply=true
sources:
  - repoURL: https://github.com/pelindung-bumi/samudera
    targetRevision: envoy-gateway-1.7.1
    path: charts/envoy-gateway
    helm:
      valueFiles:
        - $values/base/envoy-gateway/values/values-common.yaml
        - $values/overlays/pelindung-bumi/prod/envoy-gateway/values/values.yaml
  - repoURL: https://github.com/pelindung-bumi/galaksi
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/pelindung-bumi/galaksi
    targetRevision: HEAD
    path: overlays/pelindung-bumi/prod/envoy-gateway/manifests
